
    module.exports = {
 content: ['./public/index.html', './public/app.js'],
 plugins: [require('@tailwindcss/forms')],
      darkMode: "class",
      theme: {
        extend: {
          "colors": {
            "secondary-container": "#fd8a42",
            "surface-variant": "#ffdad6",
            "outline-variant": "#e1bfbb",
            "tertiary-fixed-dim": "#79db8d",
            "tertiary-container": "#005b27",
            "primary": "#760009",
            "inverse-surface": "#5a1a18",
            "surface-container-low": "#fff0ef",
            "surface-container-highest": "#ffdad6",
            "surface-container-high": "#ffe2df",
            "on-primary": "#ffffff",
            "error": "#ba1a1a",
            "surface-container-lowest": "#ffffff",
            "on-surface-variant": "#59413e",
            "background": "#fff8f7",
            "primary-fixed": "#ffdad6",
            "error-container": "#ffdad6",
            "on-tertiary-fixed": "#00210a",
            "primary-fixed-dim": "#ffb4ac",
            "on-primary-container": "#ffaaa1",
            "on-secondary-fixed": "#331200",
            "surface-tint": "#b02d29",
            "on-secondary-container": "#682c00",
            "on-background": "#3d0506",
            "on-primary-fixed": "#410002",
            "on-secondary-fixed-variant": "#763300",
            "on-secondary": "#ffffff",
            "on-error-container": "#93000a",
            "secondary": "#9b4500",
            "on-surface": "#3d0506",
            "tertiary-fixed": "#95f8a7",
            "on-tertiary-fixed-variant": "#005323",
            "surface-container": "#ffe9e7",
            "on-error": "#ffffff",
            "surface": "#fff8f7",
            "surface-dim": "#ffcfca",
            "inverse-primary": "#ffb4ac",
            "secondary-fixed": "#ffdbca",
            "outline": "#8d706d",
            "on-tertiary": "#ffffff",
            "primary-container": "#991b1b",
            "secondary-fixed-dim": "#ffb68e",
            "inverse-on-surface": "#ffedeb",
            "on-tertiary-container": "#73d487",
            "on-primary-fixed-variant": "#8e1214",
            "surface-bright": "#fff8f7",
            "tertiary": "#00411a"
          },
          "borderRadius": {
            "DEFAULT": "0.125rem",
            "lg": "0.25rem",
            "xl": "0.5rem",
            "full": "0.75rem"
          },
          "spacing": {
            "gutter-mobile": "0.75rem",
            "margin-desktop": "3rem",
            "margin": "1.5rem",
            "margin-mobile": "1rem",
            "space-xs": "0.25rem",
            "space-sm": "0.5rem",
            "gutter-desktop": "2rem",
            "space-lg": "1.5rem",
            "gutter": "1.25rem",
            "space-xl": "2.5rem",
            "space-md": "1rem"
          },
          "fontFamily": {
            "body-sm": ["Plus Jakarta Sans"],
            "label-lg": ["Plus Jakarta Sans"],
            "headline-md": ["Playfair Display"],
            "headline-lg": ["Playfair Display"],
            "label-md": ["Plus Jakarta Sans"],
            "headline-lg-mobile": ["Playfair Display"],
            "headline-md-mobile": ["Playfair Display"],
            "headline-xl-mobile": ["Playfair Display"],
            "headline-sm": ["Playfair Display"],
            "body-lg": ["Plus Jakarta Sans"],
            "title-lg": ["Plus Jakarta Sans"],
            "title-md": ["Plus Jakarta Sans"],
            "headline-xl": ["Playfair Display"],
            "title-sm": ["Plus Jakarta Sans"],
            "body-md": ["Plus Jakarta Sans"]
          },
          "fontSize": {
            "body-sm": ["12px", { "lineHeight": "18px", "fontWeight": "400" }],
            "label-lg": ["13px", { "lineHeight": "18px", "letterSpacing": "0.02em", "fontWeight": "600" }],
            "headline-md": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
            "headline-lg": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.005em", "fontWeight": "600" }],
            "label-md": ["11px", { "lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "600" }],
            "headline-lg-mobile": ["26px", { "lineHeight": "34px", "letterSpacing": "0", "fontWeight": "600" }],
            "headline-md-mobile": ["22px", { "lineHeight": "30px", "fontWeight": "600" }],
            "headline-xl-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "0", "fontWeight": "600" }],
            "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
            "body-lg": ["16px", { "lineHeight": "26px", "fontWeight": "400" }],
            "title-lg": ["18px", { "lineHeight": "26px", "fontWeight": "700" }],
            "title-md": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
            "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
            "title-sm": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
            "body-md": ["14px", { "lineHeight": "22px", "fontWeight": "400" }]
          }
        },
      },
    }
  