import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';

await mkdir('src', { recursive: true });
let html = await readFile('reference/stitch.html', 'utf8');
const config = html.match(/<script id="tailwind-config">([\s\S]*?)<\/script>/)[1];
await writeFile('tailwind.config.cjs', config.replace('tailwind.config = {', "module.exports = {\n content: ['./public/index.html', './public/app.js'],\n plugins: [require('@tailwindcss/forms')],"));
const originalStyle = html.match(/<style>([\s\S]*?)<\/style>/)[1];
await writeFile('src/stitch.css', originalStyle);
html = html.replace(/<script[\s\S]*?<\/script>/g, '').replace(/<style>[\s\S]*?<\/style>/g, '');
html = html.replace('lang="ta-IN"', 'lang="en-IN"');
html = html.replace('</head>', '<meta name="description" content="Book traditional Tamil Nadu homams and poojas with Divine Homam. Explore ceremonies and request your preferred muhurtham and Vedic priest.">\n<link rel="stylesheet" href="/styles.css?v=11">\n<script src="/app.js" defer></script>\n</head>');
html = html.replace('<body ', '<body id="top" ');
html = html.replace('<!-- Auspicious Top', '<a class="skip-link" href="#main-content">Skip to content</a>\n<!-- Auspicious Top');
html = html.replace('<main>', '<main id="main-content" tabindex="-1">');
html = html.replace('<section class="relative overflow-hidden', '<section id="hero" class="relative overflow-hidden');
const assetIds = ['2ccbd3bd79574693815c8369c836bcad.svg', '2e71a214000f40a2ac8d5eb090f599c0.png', '2e71a214000f40a2ac8d5eb090f599c0.png', 'abb969c245af41c28442e7e7ad68f4d0.png', 'b9fe05929e21420395610ef99447cd86.png', '76c961b4589e4ebb81b96ede80892185.png', '4af39cb815cb4fc581e10417cf51d804.png', '745a80e872eb45798a95ef375444b548.png'];
let imageIndex = 0;
html = html.replace(/<img\b[^>]*>/g, tag => {
  const index = imageIndex++;
  return tag.replace(/src="[^"]*"/, `src="/assets/${assetIds[index]}${index === 0 ? '?v=3' : ''}"`).replace('<img ', `<img width="${index === 0 ? 280 : 1200}" height="${index === 0 ? 60 : 896}" ${index > 1 ? 'loading="lazy"' : 'fetchpriority="high"'} decoding="async" `);
});
html = html.replace(/onclick="prefillBooking\('([^']+)'\)"/g, 'data-book="$1"');
html = html.replace(/target="_blank"/g, 'target="_blank" rel="noopener noreferrer"');
html = html.replace('id="mobileMenuBtn"', 'id="mobileMenuBtn" aria-controls="drawerOverlay" aria-expanded="false"');
html = html.replace('<div class="fixed inset-0 bg-inverse-surface/60 backdrop-blur-xs z-50 hidden transition-opacity" id="drawerOverlay">', '<dialog aria-label="Navigation" class="nav-dialog" id="drawerOverlay">');
html = html.replace('id="mobileDrawer"', 'id="mobileDrawer" tabindex="-1"');
html = html.replace(/(<\/div>\s*)<\/div>\s*<main/, '$1</dialog>\n<main');
html = html.replace('<div class="fixed inset-0 bg-inverse-surface/60 backdrop-blur-xs z-50 hidden flex items-center justify-center p-4" id="bookingModal">', '<dialog class="booking-dialog" aria-labelledby="confirmationTitle" aria-describedby="modalConfirmationText" id="bookingModal">');
html = html.replace('<h3 class="text-headline-sm font-headline-sm text-primary mb-2">Vedic Seva', '<h3 id="confirmationTitle" class="text-headline-sm font-headline-sm text-primary mb-2">Vedic Seva');
html = html.replace(/(<\/div>\s*)<\/div>\s*<!-- HOW IT WORKS/, '$1</dialog>\n<!-- HOW IT WORKS');
html = html.replace('id="fullName"', 'id="fullName" name="fullName" autocomplete="name" minlength="2" maxlength="100"');
html = html.replace('id="phone" pattern="[0-9]{10}"', 'id="phone" name="phone" autocomplete="tel-national" inputmode="tel" pattern="[0-9 +()-]{10,18}" maxlength="18"');
for (const field of ['poojaSelect', 'muhurthamTime', 'ceremonyDate', 'citySelect', 'notes']) html = html.replace(`id="${field}"`, `id="${field}" name="${field}"`);
html = html.replace('id="notes"', 'id="notes" maxlength="2000"');
html = html.replace('<!-- Submit Button -->', '<p id="formError" role="alert" tabindex="-1" hidden></p>\n<!-- Submit Button -->');
html = html.replace('id="categoryTabs"', 'id="categoryTabs" role="group" aria-label="Filter ceremonies"');
html = html.replace('id="poojaGrid"', 'id="poojaGrid" aria-label="Available ceremonies"');
html = html.replace('<!-- Catalog Bento Grid -->', '<p id="filterStatus" class="sr-only" role="status" aria-live="polite"></p>\n<!-- Catalog Bento Grid -->');
html = html.replace('class="lg:col-span-5 relative"', 'class="lg:col-span-5 relative hero-visual"');
html = html.replace('class="relative mx-auto max-w-md', 'class="hero-depth relative mx-auto max-w-md');
html = html.replace('<!-- Devotional warm vignette overlay -->', '<video id="heroVideo" class="hero-video" muted playsinline loop preload="none" aria-hidden="true" poster="/assets/2e71a214000f40a2ac8d5eb090f599c0.png"></video>\n<div class="lamp-glow" aria-hidden="true"></div>\n<button id="motionToggle" class="motion-toggle" type="button" aria-label="Pause ambient motion" aria-pressed="false"><span aria-hidden="true">Ⅱ</span></button>\n<!-- Devotional warm vignette overlay -->');
html = html.replace(/<span class="w-2.5 h-2.5 rounded-full bg-tertiary-container animate-pulse"><\/span>/, '<span class="w-2.5 h-2.5 rounded-full bg-tertiary-container"></span>');
await writeFile('public/index.html', html);
await copyFile('hero_section.mp4', 'public/assets/hero.mp4');
console.log('Imported Stitch content, local imagery, and accessible page structure.');
